### ISSUE TITLE
iOS AVPlayer can't play with the url returned by the livestream

### ISSUE THREAD

**Issue by longvo-dirox** [apivideo/ios-sdk#3]
I'm implementing iOS and using AVPlayer, the url I passed to AVPlayer is like this https://live.api.video/li5x86cfQOyoEyXDlwbDPuv.m3u8 , this is the HLS url I received from a livestream I created, but the AVPlayer can't play this HLS url
(Side note: in addition to the 'HLS' url, the livestream I created also provides a 'player' url such as https://live.api.video/li5x86cfQOyoEyXDlwbDPuv.m3u8 , I can paste this player url to a web browser and it can load the video successfully, but my problem is using AVPlayer in iOS, I couln't play either the 'HLS' or 'player' url, can you provide some of your idea about this please? Thank you very much

**Comment by RomainPetit1** [comment]
Hello,

**Comment by RomainPetit1** [comment]
Our technical team is analyzing and trying to reproduce your problem. It appears that under the following conditions: player api + wkwebview it works well. We will get back to you as soon as we have a solution. In the meantime we advise you to integrate the player under the conditions described above.

**Comment by RomainPetit1** [comment]
Hello, we’ve solved the problem. So now you can use the AVPlayer and HLS url without any problems. Please let me know if you are still experiencing difficulties, otherwise I will close this issue
